version: '3'
services:
  web:
    image: 336898993714.dkr.ecr.us-east-1.amazonaws.com/mphelps-jump-capstone:latest
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: jump-capstone
        awslogs-region: us-east-1
        awslogs-stream-prefix: web
